FROM nginx:alpine
RUN apk update && apk add certbot certbot-nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/conf /etc/nginx/conf.d/conf.conf
#COPY ./init.sh /etc/nginx/init.sh
ARG NOSTR_DOMAIN
ARG EMAIL

#RUN certbot run -n --nginx --agree-tos -d ${NOSTR_DOMAIN}  -m  ${EMAIL}  --redirect
