FROM nginx:alpine
RUN apk update && apk add certbot certbot-nginx
#COPY ./default_nginx /etc/nginx/conf.d/default_holder.conf
COPY ./nginx/conf /etc/nginx/conf.d/conf.conf
ARG NOSTR_DOMAIN
ARG EMAIL

#RUN certbot run -n --nginx --agree-tos -d ${NOSTR_DOMAIN}  -m  ${EMAIL}  --redirect
