version: '2.1'

services:
  relay:
    container_name: relay
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8008:8008"
    environment:
      - DD_AGENT_HOST="nostpyrelay"
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_DB=nostpy
      - POSTGRES_USER=nostpy
      - POSTGRES_PASSWORD=nostpy
      - DATABASE_URL=postgresql://nostpy:nostpy@postgres:5432/nostpy
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
    volumes:
      - ./errors:/errors
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      relay-network:
        ipv4_address: 172.20.0.2


  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=nostpy
      - POSTGRES_USER=nostpy
      - POSTGRES_PASSWORD=nostpy
    ports:
      - 5432:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nostpy"] # database username here - nostr, should be changed if other user
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      relay-network:
        ipv4_address: 172.20.0.3

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
      args:
        NOSTR_DOMAIN: nostr.dojotunnel.online
        EMAIL: bhartford419@gmail.com
    environment:
      - NOSTR_DOMAIN=nostr.dojotunnel.online
      - PROXY_PASS_IP=172.20.0.2
      - PORT=8008
    container_name: nginx-reverse-proxy
    ports:
      - 80:80
      - 443:443
    command: ash -c "certbot run -n --nginx --agree-tos -d nostr.dojotunnel.online  -m  bhartford419@gmail.com --redirect"
    networks:
      relay-network:
        ipv4_address: 172.20.0.4
networks:
  relay-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24